##################################################################################################################################
#################################[ DeathCost DevBuild 1.0.0 ]#####################################################################
###############################[ Developed By AcktarOfficial ]####################################################################
#############################[ Subscribe: https://sub2acktar.xyz ]################################################################
##################################################################################################################################

#Amount of money to remove from player when he dies
Death-cost: '575'

#wheather to enable percentage or now (true/false)
percentage-switch: 'true'
percent: '25'

#message to send to player when money gets reduce/onDeath
message: '§l§f(§bDeath§dCost§f)§r§c You Died And Lost {money} Nob§7!'
